-- 아직 순서 고려 안함
DROP TABLE BOARD;
DROP TABLE BOARD_REPLY;
DROP TABLE MEMBER;
DROP TABLE ROOM;
DROP TABLE CART;
DROP TABLE RESERVATION;
DROP TABLE EVENT;

CREATE TABLE EVENT
(
    ENO NUMBER,
    ONSALE NUMBER,
    ENAME VARCHAR2(100),
    ESTART DATE,
    EEND DATE,
    EPERCENT NUMBER,
    EDUPLICATE NUMBER
);

CREATE TABLE RESERVATION
(
    RENO NUMBER,
    RNO NUMBER NOT NULL,
    MNO NUMBER NOT NULL,
    PEOPLE NUMBER,
    CHECK_IN DATE,
    CHECK_OUT DATE,
    FOOD NUMBER
);

CREATE TABLE CART
(
    CNO NUMBER NOT NULL,
    MID VARCHAR2(50) NOT NULL,
    RNO NUMBER NOT NULL,
    CAMOUNT NUMBER NOT NULL,
    CPRICE NUMBER
);

CREATE TABLE ROOM
(
    RNO NUMBER NOT NULL,
    RNAME VARCHAR2(100) NOT NULL UNIQUE,
    RPRICE NUMBER NOT NULL,
    RGRADE NUMBER NOT NULL,
    RIMG VARCHAR2(100),
    RACCEPT NUMBER,
    RSIZE NUMBER
);

CREATE TABLE MEMBER
(
    MNO NUMBER,
    MNAME VARCHAR2(50) NOT NULL,
    MID VARCHAR2(50) NOT NULL UNIQUE,
    MPW VARCHAR2(50) NOT NULL,
    MEMAIL VARCHAR2(100) NOT NULL UNIQUE,
    MPHONE VARCHAR2(20) NOT NULL,
    MGRADE VARCHAR2(20),
    MREGDATE DATE
);

CREATE TABLE BOARD_REPLY
(
    IDX NUMBER,
    WRITER VARCHAR2(50) NOT NULL,
    CONTENT VARCHAR2(2000),
    BIDX NUMBER NOT NULL,
    POSTDATE DATE
);

CREATE TABLE BOARD
(
    BIDX NUMBER NOT NULL,
    MID VARCHAR2(50) NOT NULL,
    BTITLE VARCHAR2(100),
    BCONTENT VARCHAR2(2000),
    BHIT NUMBER,
    BFILENAME VARCHAR2(2000),
    BPOSTDATE DATE
);



ALTER TABLE MEMBER ADD CONSTRAINT MEMBER_PK PRIMARY KEY(MNO);
ALTER TABLE BOARD ADD CONSTRAINT BOARD_PK PRIMARY KEY(BIDX);
ALTER TABLE CART ADD CONSTRAINT CART_PK PRIMARY KEY(CNO);
ALTER TABLE ROOM ADD CONSTRAINT ROOM_PK PRIMARY KEY(RNO);
ALTER TABLE RESERVATION ADD CONSTRAINT RESERVATION_PK PRIMARY KEY(RENO);
ALTER TABLE EVENT ADD CONSTRAINT EVENT_PK PRIMARY KEY(ENO);
ALTER TABLE BOARD_REPLY ADD CONSTRAINT BOARD_REPLY_PK PRIMARY KEY(IDX);


ALTER TABLE BOARD ADD CONSTRAINT BOARD_MEMBER_FK FOREIGN KEY(MID) REFERENCES MEMBER(MID);
ALTER TABLE CART ADD CONSTRAINT CART_MEMBER_FK FOREIGN KEY(MID) REFERENCES MEMBER(MID);
ALTER TABLE CART ADD CONSTRAINT CART_ROOM_FK FOREIGN KEY(RNO) REFERENCES ROOM(RNO);
ALTER TABLE BOARD_REPLY ADD CONSTRAINT BOARD_REPLY_MEMBER_FK FOREIGN KEY(WRITER) REFERENCES MEMBER(MID);
ALTER TABLE BOARD_REPLY ADD CONSTRAINT BOARD_REPLY_BOARD_FK FOREIGN KEY(BIDX) REFERENCES BOARD(BIDX);
ALTER TABLE RESERVATION ADD CONSTRAINT RESERVATION_ROOM_FK FOREIGN KEY(RNO) REFERENCES ROOM(RNO);
ALTER TABLE RESERVATION ADD CONSTRAINT RESERVATION_MEMBER_FK FOREIGN KEY(MNO) REFERENCES MEMBER(MNO);

CREATE SEQUENCE MEMBER_SEQ INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE;
CREATE SEQUENCE BOARD_SEQ INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE;
CREATE SEQUENCE CART_SEQ INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE;
CREATE SEQUENCE ROOM_SEQ INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE;
CREATE SEQUENCE RESERVATION_SEQ INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE;
CREATE SEQUENCE EVENT_SEQ INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE NOCACHE;


INSERT INTO BUYS VALUES (MEMBER_SEQ.NEXTVAL, 'KHD', '운동화', '신발', 30, 2);
SELECT * FROM ROOM;

