/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.65
 * Generated at: 2021-07-31 13:04:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.room;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class priceRoom_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("  \r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../layout/header.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("title", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("로그인", request.getCharacterEncoding()), out, false);
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  \t<script type=\"text/javascript\">\r\n");
      out.write("\t  \tonload = function(){\r\n");
      out.write("\t  \t\tvar thumbnails = document.getElementsByClassName('thumbnail');\r\n");
      out.write("\t\t\t// var thumbnails = document.querySelectorAll('.thumbnail');\r\n");
      out.write("\t\t\tfor (let i = 0; i < thumbnails.length; i++) {\r\n");
      out.write("\t\t\t\tthumbnails[i].addEventListener('click', function(){\r\n");
      out.write("\t\t\t\t\t// data-img 속성 값을 저장하고 있는 이벤트 객체 : this\r\n");
      out.write("\t\t\t\t\t// this.getAttribute('data-img')\r\n");
      out.write("\t\t\t\t\t// this.dataset.img\r\n");
      out.write("\t\t\t\t\tdocument.getElementById('large-image').setAttribute('src', this.dataset.img);\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t    document.getElementById('amenity').onclick = function(){\r\n");
      out.write("\t\t    \twindow.open('amenity.do', '', 'width=640, height=480, resizable=no');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tdocument.getElementById('satellite channel').onclick = function(){\r\n");
      out.write("\t\t    \twindow.open('satelliteChannel.do', '', 'width=520, height=520, resizable=no');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tdocument.getElementById('floorPlan').onclick = function(){\r\n");
      out.write("\t\t    \twindow.open('floorPlan.do', '', 'width=640, height=480, resizable=no');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tdocument.getElementById('inquire').onclick = function(){\r\n");
      out.write("\t\t    \tlocation.href= \"inquire.do\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tdocument.getElementById('reservation').onclick = function(){\r\n");
      out.write("\t\t    \tlocation.href= \"reservation.do\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tdocument.getElementById('privacy').onclick = function(){\r\n");
      out.write("\t\t    \twindow.open('privacy.do', '', 'width=640, height=480, resizable=no');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tdocument.getElementById('term').onclick = function(){\r\n");
      out.write("\t\t    \twindow.open('term.do', '', 'width=640, height=480, resizable=no');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tdocument.getElementById('noEmail').onclick = function(){\r\n");
      out.write("\t\t    \twindow.open('noEmail.do', '', 'width=400, height=352, resizable=no');\r\n");
      out.write("\t\t\t} \r\n");
      out.write("\t\t\tgetDate();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$('<input type=\"hidden\" name=\"page\" value=\"priceRoom.do\">')\r\n");
      out.write("\t\t\t.appendTo( $('.form') )\r\n");
      out.write("\t\t\t$('<input type=\"hidden\" name=\"rNo\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${roomDTO.RNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">')\r\n");
      out.write("\t\t\t.appendTo( $('.form') )\r\n");
      out.write("\t  \t}\r\n");
      out.write("  \t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t\t<div id=\"container\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<br><br>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<h1>룸 가격 페이지</h1>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<form id=\"f\" method=\"post\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"no\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${roomDTO.RNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" disabled>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t룸 이름<br>\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"rName\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${roomDTO.RName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" disabled><br><br>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t룸 가격<br>\r\n");
      out.write("\t\t\t\t<input type=\"number\" name=\"rPrice\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${roomDTO.RPrice}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" disabled><br><br>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t룸 등급<br>\r\n");
      out.write("\t\t\t\t<input type=\"number\" name=\"rGrade\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${roomDTO.RGrade}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" disabled><br><br>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t룸 수용인원<br>\r\n");
      out.write("\t\t\t\t<input type=\"number\" name=\"rAccept\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${roomDTO.RAccept}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" disabled><br><br>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t룸 사이즈<br>\r\n");
      out.write("\t\t\t\t<input type=\"number\" name=\"rSize\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${roomDTO.RSize}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" disabled><br><br>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t룸 이미지<br>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${roomDTO.RImg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" id=\"large-image\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<ul class=\"rImg\">\r\n");
      out.write("\t\t\t\t\t<li><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${roomDTO.RImg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"thumbnail\" data-img=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${roomDTO.RImg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></li>\r\n");
      out.write("\t\t\t\t\t<li><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${roomDTO.RImg1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"thumbnail\" data-img=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${roomDTO.RImg1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></li>\r\n");
      out.write("\t\t\t\t\t<li><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${roomDTO.RImg2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"thumbnail\" data-img=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${roomDTO.RImg2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></li>\r\n");
      out.write("\t\t\t\t\t<li><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${roomDTO.RImg3}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"thumbnail\" data-img=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${roomDTO.RImg3}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></li>\r\n");
      out.write("\t\t\t\t\t<li><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${roomDTO.RImg4}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"thumbnail\" data-img=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${roomDTO.RImg4}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></li>\r\n");
      out.write("\t\t\t\t\t<li><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${roomDTO.RImg5}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"thumbnail\" data-img=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${roomDTO.RImg5}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"leftArea\">\r\n");
      out.write("\t\t\t\t<img alt=\"left\" src=\"resources/images/priceRoom/leftArea.PNG\"><br>\r\n");
      out.write("\t\t\t\t<img style=\"cursor: pointer;\" id=\"amenity\" alt=\"객실어매니티\" src=\"resources/images/priceRoom/객실어매니티.PNG\">\r\n");
      out.write("\t\t\t\t<table class=\"tableRoomInfo\">\r\n");
      out.write("\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t<tr class=\"first\">\r\n");
      out.write("\t\t\t\t\t\t\t<th scope=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t객실이용\r\n");
      out.write("\t\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"introList\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"first\">55인치 스마트 TV(위성 TV 48개 채널)  <span style=\"cursor: pointer;\" id=\"satellite channel\"><i class=\"fas fa-tv\">위성채널정보 보기</i></span></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>50~100Mbps 초고속 유·무선(wifi) 인터넷 무료</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>220V, 110V 전압 사용 가능</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>커피·차 티백 무료 제공</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>엑스트라 베드 1개 추가 36,300원/1박</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>베이비 크립(무료)</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th scope=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t부대시설\r\n");
      out.write("\t\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"introList\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"first\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t피트니스 클럽 이용 안내\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t- 체육관(Gym) 무료 이용(만 16세 이상 입장 가능)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t- 실내 수영장 무료 이용(만 13세 이상 입장 가능)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;(단, 주말 및 공휴일에는 성인 보호자의 보호 하에\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;만 13세 미만인 고객이 이용 가능하며,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;신장 140cm 미만인 고객은 성인 보호자의 보호 하에\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;구명조끼 착용 시 이용 가능)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t- 사우나 이용시 유료(만 13세 이상 입장 가능)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t- 피트니스 클럽은 매월 세 번째 수요일 정기휴일입니다.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"last\">투숙 기간 내 무료 주차 가능</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr class=\"last\">\r\n");
      out.write("\t\t\t\t\t\t\t<th scope=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t룸서비스\r\n");
      out.write("\t\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"introList\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"first\">객실에서 즐기실 수 있는 다양한 룸서비스 메뉴가 준비되어 있습니다.</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>식사 및 음료 : 24시간 서비스</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>중식, 일식 : 점심 12:00~14:00, 저녁 18:00~21:30</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"last\"><a href=\"download.do\"><img alt=\"다운로드\" src=\"resources/images/priceRoom/룸서비스메뉴다운로드.PNG\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"rightArea\">\r\n");
      out.write("\t\t\t\t<ul class=\"btnSet\">\r\n");
      out.write("\t\t\t\t\t<li class=\"first\">\r\n");
      out.write("\t\t\t\t\t\t<img style=\"cursor: pointer;\" id=\"floorPlan\" src=\"resources/images/priceRoom/floorPlan.JPG\" alt=\"도면보기\">\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<img style=\"cursor: pointer;\" id=\"inquire\" src=\"resources/images/priceRoom/inquire.JPG\" alt=\"문의하기\">\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"last\">\r\n");
      out.write("\t\t\t\t\t\t<img style=\"cursor: pointer;\" id=\"reservation\" src=\"resources/images/priceRoom/reservation.JPG\" alt=\"예약하기\">\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<div class=\"HotelInfoBox\">\r\n");
      out.write("\t\t\t\t\t<div class=\"HotelBoxTop\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"conTitle1\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3 class=\"title\">Hotel Info.</h3>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"title\">조식 이용 안내</p>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"useIntro\">\r\n");
      out.write("\t\t\t\t\t\t\t<p>- 더 파크뷰 06:00~10:00(주중/주말/공휴일)</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p>- 더 라이브러리 08:00~11:30</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p style=\"text-indent: -16px; padding-left: 24px;\">\r\n");
      out.write("\t\t\t\t\t\t\t※ 현재 더 라이브러리는 코로나19로 인한 운영시간 \r\n");
      out.write("\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t  축소로 조식 운영을 하지 않고 있사오니 이용에 \r\n");
      out.write("\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t  참고 부탁드립니다.\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"introBtm\" style=\"min-height: 0px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"title\">체크인/체크아웃 시간</p>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"useIntro\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>- 체크인 : 오후 3시 이후</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>- 체크아웃 : 낮 12시 </p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>※ 2021년 10월 1일부터 체크인은 오후 2시 이후, 체크아웃은 오전 11시까지로 변경됩니다.</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"introBtm\" style=\"min-height: 0px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"title\">취소/변경 및 노쇼(No-show) 안내</p>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"useIntro\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p style=\"letter-spacing: -0.3px;\">- 숙박 예정일 1일 전 18시까지는 위약금 없음</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p style=\"letter-spacing: -0.3px;\">- 숙박 예정일 1일 전 18시 이후 취소/변경/노쇼 발생 시</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p style=\"padding: 0px 18px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t 성수기(5월~10월, 12월 24일~31일) :\r\n");
      out.write("\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t 최초 1일 숙박 요금의 80%가 위약금으로 부과\r\n");
      out.write("\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t 비수기(성수기 외 기간) :\r\n");
      out.write("\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t 최초 1일 숙박 요금의 10%가 위약금으로 부과\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../layout/footer.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("title", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("로그인", request.getCharacterEncoding()), out, false);
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
