/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.65
 * Generated at: 2021-08-01 05:32:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.reservation;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class revInfoPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/spring0303/project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SpringD/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1624616931203L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html >\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta  charset=UTF-8>\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\" integrity=\"sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"resources/css/loginWindow.css\"> \r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\tfn_check();\t//체크박스 누름 => 회원과 같은 정보 뿌려줌\r\n");
      out.write("\t\tfn_emailCheck();\t//이메일 형식검사\r\n");
      out.write("\t\tfn_email_code();\t//이메일 확인 버튼 누름\r\n");
      out.write("\t\tfn_email_auth();\t//이메일 코드 확인 검사\r\n");
      out.write("\t\tfn_doReservation();\t//예약하기 버튼 누름\r\n");
      out.write("\t\tfn_closeLogin();\t// 로그인창에서 x 클릭시 로그인창 닫히고 , 열림반복\r\n");
      out.write("\t\tfn_toggle_mode(); \t// 관리자 로그인 모드 / 회원 로그인 모드로 변경하는 버튼\r\n");
      out.write("\t});\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t//체크박스('회원정보와 동일하다') 클릭시, 정보 뿌려줌\r\n");
      out.write("\tfunction fn_check(){\r\n");
      out.write("\t\t$('#sameUser_box').click(function(){\r\n");
      out.write("\t\t\tif($(\"input:checkbox\").is(\":checked\") == true) {\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//로그인 안되어있을시 , 로그인 div보여주기\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t//로그인 되어있을시, 그냥 회원정보 띄워주기\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}//if끝\r\n");
      out.write("\t\t\telse{\t// 체크 되어있는 상태일 때\r\n");
      out.write("\t\t\t\tauthPass = false;\r\n");
      out.write("\t\t\t\t$('#booker').val('');\r\n");
      out.write("\t\t\t\t$('#reEmail').val('');\r\n");
      out.write("\t\t\t\t$('#tel').val('');\r\n");
      out.write("\t\t\t\t$('#emailChk').toggleClass('hide');\r\n");
      out.write("\t\t\t\t$('#email').toggleClass('hide');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t \r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t//이메일 형식 검사\t\r\n");
      out.write("\tfunction fn_emailCheck(){\r\n");
      out.write("\t\t$('#reEmail').blur(function(){\r\n");
      out.write("\t\t\tvar regEmail =/^[0-9a-zA-Z]([-_.]?[0-9a-zA-Z])*@[0-9a-zA-Z]([-_.]?[0-9a-zA-Z])*.[a-zA-Z]{2,3}$/i;\r\n");
      out.write("\t\t\tif(!regEmail.test($('#reEmail').val())){ // reEmail정규식 조건을 통과하지 못 했을 경우\r\n");
      out.write("\t\t\t\t$('.email_result').text('이메일 형식이 잘못입력되었습니다.');\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}else{//정규식 통과시\r\n");
      out.write("\t\t\t\t$('.email_result').text('');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tfn_email_code();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t// 이메일 인증코드 받기(emailCode)\r\n");
      out.write("\t// 이메일 인증코드 받기(root-context에서 이메일 bean 생성)\r\n");
      out.write("\tfunction fn_email_code(){\r\n");
      out.write("\t\t$('#email_code_btn').click(function(){\r\n");
      out.write("\t\t\tif($('#reEmail').val() == ''){\r\n");
      out.write("\t\t\t\talert('이메일을 입력하세요.');\r\n");
      out.write("\t\t\t\t$('#reEmail').focus();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl: 'emailCode.do',\r\n");
      out.write("\t\t\t\ttype: 'get',\r\n");
      out.write("\t\t\t\tdata: 'mEmail=' + $('#reEmail').val(),\r\n");
      out.write("\t\t\t\tdataType: 'json',\r\n");
      out.write("\t\t\t\tsuccess: function(resultMap){\r\n");
      out.write("\t\t\t\t\talert('인증코드가 발송되었습니다. 메일을 확인하세요.');\r\n");
      out.write("\t\t\t\t\tfn_email_auth(resultMap.authCode);\r\n");
      out.write("\t\t\t\t\talert(resultMap.authCode);\t//편의상 달아놓았습니다.. ^^!\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror: function(xhr, textStatus, errorThrown) {\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t// 이메일 인증(emailAuth)\r\n");
      out.write("\tvar authPass = false;\r\n");
      out.write("\tfunction fn_email_auth(authCode){\r\n");
      out.write("\t\t$('#email_auth_btn').click(function(){\r\n");
      out.write("\t\t\tif(authCode == $('#user_key').val()){\r\n");
      out.write("\t\t\t\t$('.emailAuth_result').text('인증되었습니다.');\r\n");
      out.write("\t\t\t\tauthPass = true;\r\n");
      out.write("\t\t\t} else{\r\n");
      out.write("\t\t\t\t$('.emailAuth_result').text('인증에 실패했습니다. 다시 시도해주세요.');\r\n");
      out.write("\t\t\t\tauthPass = false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t//(1.로그인 했는지) => 2.이메일 인증했는지 + (이름,휴대폰 적었는지) => 3. 됐다면 (영수증)페이지 이동 / 아니라면 안내문자\r\n");
      out.write("\tfunction fn_doReservation(){\r\n");
      out.write("\t\t$('#doReservation_btn').click(function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\tif($('#booker').val()==''){\r\n");
      out.write("\t\t\t\t\talert('예약자명은 필수입니다.');\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}else if($('#tel').val()==''){\r\n");
      out.write("\t\t\t\t\talert('전화번호는 필수입니다.');\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}else if( authPass==false){\r\n");
      out.write("\t\t\t\t\talert('이메일 인증은 필수입니다.');\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t$('#f').attr('action','receiptPage.do');\r\n");
      out.write("\t\t\t\t\t$('#f').submit();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t/*");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write("*/\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t//로그인 관련 script\r\n");
      out.write("\t\r\n");
      out.write("    function fn_closeLogin(){\r\n");
      out.write("\t\t\t$('.cancel_btn').on('click',function(){\r\n");
      out.write("\t\t\t\t$('.form').toggleClass('hide');\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$('#closeLogin').on('click',function(){\r\n");
      out.write("\t\t\t\t$('.form').toggleClass('hide');\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction fn_toggle_mode(){\r\n");
      out.write("\t\t$('#mem_to_admin').click(function(){\r\n");
      out.write("\t\t\t$('#mem_mode').toggleClass('disabled');\r\n");
      out.write("\t\t\t$('#admin_mode').toggleClass('disabled');\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#admin_to_mem ').click(function(){\r\n");
      out.write("\t\t\t$('#mem_mode').toggleClass('disabled');\r\n");
      out.write("\t\t\t$('#admin_mode').toggleClass('disabled');\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("\t\ttable,tr,td{\r\n");
      out.write("\t\t border: 1px solid pink;\r\n");
      out.write("\t\t text-align: center;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<h1>예약정보</h1>\r\n");
      out.write("\t<form id=\"f\">\r\n");
      out.write("\t<!-- 파라미터 값들(hidden) -->\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"rNo\" name=\"rNo\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t \t<input type=\"hidden\" name=\"checkIn\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${checkIn}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t \t<input type=\"hidden\" name=\"checkOut\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${checkOut}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t \t<input type=\"hidden\" name=\"people\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${people}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t \t<input type=\"hidden\" name=\"food\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${food}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t \t<input type=\"hidden\" name=\"totalPay\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalPay}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t \t\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t\t<thead>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<!-- 체크시 ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("의 이름/이메일/휴대폰  뿌려줌 -->\r\n");
      out.write("\t\t\t\t\t<td colspan=\"2\"> <label><input type=\"checkbox\" id=\"sameUser_box\"> 회원정보와 동일합니다 </label> </td> \r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</thead>\r\n");
      out.write("\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>이름</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"booker\" id=\"booker\"> </td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr id=\"email\">\r\n");
      out.write("\t\t\t\t\t<td>이메일</td>\r\n");
      out.write("\t\t\t\t\t<!-- 이메일 인증할 계정 + 이메일 정규식 적용 -->\r\n");
      out.write("\t\t\t\t\t<td> \r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"reEmail\" id=\"reEmail\"> \r\n");
      out.write("\t\t\t\t\t<input type=\"button\" id=\"email_code_btn\"  value=\"인증번호 전송\"><br>\r\n");
      out.write("\t\t\t\t\t<span class=\"email_result\"></span>  \r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr id=\"emailChk\">\r\n");
      out.write("\t\t\t\t\t<td>이메일 인증코드</td>\r\n");
      out.write("\t\t\t\t\t<!-- 이메일 인증하기 -->\r\n");
      out.write("\t\t\t\t\t<td> \r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" id=\"user_key\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" id=\"email_auth_btn\" value=\"인증확인\"> <br>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"emailAuth_result\"></span> \r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>휴대폰 </td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"tel\" id=\"tel\"> </td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>요청사항</td>\r\n");
      out.write("\t\t\t\t\t<td><textarea rows=\"10\" cols=\"40\" name=\"note\"></textarea> </td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</tbody>\r\n");
      out.write("\t\t\t<tfoot>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"2\"> <input type=\"button\" id=\"doReservation_btn\" value=\"예약하기\"> </td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</tfoot>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"mem_mode\" class=\"myMenu\">\r\n");
      out.write("\t\t<form action=\"login.do\" method=\"post\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" id=\"rNo\" name=\"rNo\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t \t<input type=\"hidden\" name=\"checkIn\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${checkIn}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t \t<input type=\"hidden\" name=\"checkOut\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${checkOut}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t \t<input type=\"hidden\" name=\"people\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${people}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t \t<input type=\"hidden\" name=\"food\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${food}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t \t<input type=\"hidden\" name=\"totalPay\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalPay}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t \t\r\n");
      out.write("  \t   \t \t<div class=\"form hide\">\r\n");
      out.write("  \t   \t \t\t<input type=\"hidden\" name=\"page\" value=\"revInfoPage.do\">\r\n");
      out.write("  \t   \t \t\t<h2 style=\"text-align:center\">회원 로그인</h2>\r\n");
      out.write("\t\t\t\t<a id=\"closeLogin\"><i class=\"fas fa-times fa-3x\"></i></a>\r\n");
      out.write("   \t\t\t\t <div class=\"form2\">\r\n");
      out.write("     \t\t\t\t<div class=\"form3\">\r\n");
      out.write("     \t\t\t\t\t<label for=\"id\">아이디</label><input type=\"text\" name=\"mId\" id=\"mId\">\r\n");
      out.write("      \t\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("      \t\t\t\t\t<label for=\"password\">비밀번호</label><input type=\"password\" name=\"mPw\" id=\"mPw\">\r\n");
      out.write("     \t\t\t\t</div>\t<!-- form3 -->\r\n");
      out.write("     \t\t\t\t<input type=\"submit\" id=\"login_btn\" value=\"로그인\">\r\n");
      out.write("     \t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("     \t\t\t\t<div class=\"form4\">\r\n");
      out.write("      \t\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("     \t\t\t\t\t\t<label><input type=\"button\" value=\"회원가입\"></label>\r\n");
      out.write("     \t\t\t\t\t\t<label><input type=\"button\" value=\"아이디/비밀번호 찾기\"></label>\r\n");
      out.write("     \t\t\t\t\t\t<label><input type=\"button\" id=\"mem_to_admin\" value=\"관리자로 로그인하기\"></label>\r\n");
      out.write("\t\t\t\t\t</div>\t<!-- form4 -->\r\n");
      out.write("\t\t\t\t</div>\t<!-- form2 -->\r\n");
      out.write("\t\t\t</div>\t<!-- form -->\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\t<!-- myMenu -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"admin_mode\" class=\"myMenu disabled\">\r\n");
      out.write("\t\t\t<form action=\"loginAdmin.do\" method=\"post\">\r\n");
      out.write("  \t   \t \t<div class=\"form hide\">\r\n");
      out.write("  \t   \t \t\t<input type=\"hidden\" name=\"page\" value=\"revInfoPage.do\">\r\n");
      out.write("  \t   \t \t\t<h2 style=\"text-align:center\">관리자 로그인</h2>\r\n");
      out.write("\t\t\t\t<a id=\"closeLogin\"><i class=\"fas fa-times fa-3x\"></i></a>\r\n");
      out.write("   \t\t\t\t <div class=\"form2\">\r\n");
      out.write("     \t\t\t\t<div class=\"form3\">\r\n");
      out.write("     \t\t\t\t\t<label for=\"id\">아이디</label><input type=\"text\" name=\"mId\" id=\"mId\">\r\n");
      out.write("      \t\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("      \t\t\t\t\t<label for=\"password\">비밀번호</label><input type=\"password\" name=\"mPw\" id=\"mPw\">\r\n");
      out.write("     \t\t\t\t</div>\t<!-- form3 -->\r\n");
      out.write("     \t\t\t\t<input type=\"submit\" id=\"login_btn\" value=\"로그인\">\r\n");
      out.write("     \t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("     \t\t\t\t<div class=\"form4\">\r\n");
      out.write("      \t\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("     \t\t\t\t\t\t<label><input type=\"button\" id=\"admin_to_mem\" value=\"회원으로 로그인하기\"></label>\r\n");
      out.write("\t\t\t\t\t</div>\t<!-- form4 -->\r\n");
      out.write("\t\t\t\t</div>\t<!-- form2 -->\r\n");
      out.write("\t\t\t</div>\t<!-- form -->\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\t<!-- myMenu -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/reservation/revInfoPage.jsp(30,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty loginUser}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\tif(confirm('로그인 하시겠습니까 ?')){\r\n");
          out.write("\t\t\t\t\t\t//로그인 툴 보여주기\r\n");
          out.write("\t\t\t\t\t\t$('.form').toggleClass('hide');\r\n");
          out.write("\t\t\t\t\t} \r\n");
          out.write("\t\t\t\t\t$('input').prop(\"checked\", false);\t//로그인 안할시, 체크박스 해제\t\r\n");
          out.write("\t\t\t\t\t//$('.form').toggleClass('hide');\t 회원제로만 운영할시 , if문~$('input') 삭제하고 이것만 넣어주면 댐\r\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/reservation/revInfoPage.jsp(40,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ not empty loginUser}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\tauthPass = true;\r\n");
          out.write("\t\t\t\t\t$('#booker').val('");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.getMName()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("');\r\n");
          out.write("\t\t\t\t\t$('#reEmail').val('");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.getMEmail()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("');\r\n");
          out.write("\t\t\t\t\t$('#tel').val('");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.getMPhone()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("');\r\n");
          out.write("\t\t\t\t\t$('#emailChk').toggleClass('hide');\r\n");
          out.write("\t\t\t\t\t$('#email').toggleClass('hide');\r\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/views/reservation/revInfoPage.jsp(138,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty loginUser}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t$('.form').toggleClass('hide');\r\n");
          out.write("\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent(null);
      // /WEB-INF/views/reservation/revInfoPage.jsp(142,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty loginUser}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("*/\r\n");
          out.write("\t\t\t/*");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }
}
